# Generated by Django 3.2.5 on 2021-08-12 14:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='kospi_kosdaq_history',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section', models.CharField(max_length=128, verbose_name='section')),
                ('date', models.CharField(max_length=128, verbose_name='date')),
                ('open', models.FloatField(verbose_name='open')),
                ('high', models.FloatField(verbose_name='high')),
                ('low', models.FloatField(verbose_name='low')),
                ('close', models.FloatField(verbose_name='close')),
            ],
        ),
        migrations.CreateModel(
            name='Stockhistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=128, verbose_name='code')),
                ('name', models.CharField(max_length=128, verbose_name='name')),
                ('section', models.CharField(max_length=128, verbose_name='section')),
                ('date', models.CharField(max_length=128, verbose_name='date')),
                ('open', models.FloatField(verbose_name='open')),
                ('high', models.FloatField(verbose_name='high')),
                ('low', models.FloatField(verbose_name='low')),
                ('close', models.FloatField(verbose_name='close')),
            ],
        ),
        migrations.CreateModel(
            name='Stocklist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=128, verbose_name='회사이름')),
                ('code', models.CharField(max_length=32, verbose_name='코드이름')),
                ('KOSPI200', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='주식이름')),
                ('code', models.CharField(max_length=32, verbose_name='주식코드')),
                ('quantity', models.FloatField(verbose_name='구매 개수')),
                ('buy_price', models.CharField(blank=True, max_length=128, verbose_name='구매가')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='구매날짜')),
                ('KOSPI200', models.BooleanField(default=False)),
                ('backtesting_past_price', models.CharField(blank=True, max_length=128, verbose_name='백테스팅용 과거 가격표')),
                ('real_price', models.CharField(blank=True, max_length=128, verbose_name='실시간가격')),
                ('profit_rate', models.CharField(blank=True, max_length=128, verbose_name='수익률')),
                ('profit_asset', models.CharField(blank=True, max_length=128, verbose_name='주식자산')),
                ('property', models.CharField(blank=True, max_length=128, verbose_name='보유비율')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.account', verbose_name='계정')),
            ],
        ),
    ]
