# Generated by Django 3.2.5 on 2021-08-12 14:48

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CryptoTicker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='종목 이름')),
                ('ticker', models.CharField(max_length=20, verbose_name='티커')),
                ('market', models.CharField(max_length=20, verbose_name='마켓')),
            ],
        ),
        migrations.CreateModel(
            name='Crypto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(default=django.utils.timezone.now, null=True)),
                ('name', models.CharField(default='default_name', max_length=20, verbose_name='종목 이름')),
                ('ticker', models.CharField(max_length=20, verbose_name='티커')),
                ('market', models.CharField(default='defalut_market', max_length=20, verbose_name='마켓')),
                ('quantity', models.FloatField(default=0, verbose_name='보유량')),
                ('buy_price', models.FloatField(default=0, verbose_name='매수가격')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.account', verbose_name='계정')),
            ],
        ),
    ]
